#!/usr/bin/env bash
set -e

OS=$(cut -f2 <<<$(lsb_release -i))
! [[ -x $(command -v gnome-shell) ]]
GUI=$?

if [[ ! "$OS" =~ ^(Ubuntu|EndeavourOS|Arch)$ ]]; then
	echo "Unknown distro"
	exit 1
fi

source ./helpers.sh

# Confirm sudo
sudo echo

if [[ "$OS" = "Ubuntu" ]]; then
	VERSION=$(cut -f2 <<<$(lsb_release -r))
	export DEBIAN_FRONTEND=noninteractive

	sudo apt install -y software-properties-common
	sudo add-apt-repository ppa:neovim-ppa/unstable -y
	sudo apt update
	sudo apt upgrade -y

	sudo -E apt install -y build-essential neofetch python3-pip tmux curl python3-virtualenvwrapper fd-find telegram-desktop htop systemd-coredump zsh bat unar neovim unzip

	if [[ "$VERSION" =~ ^(22.04|22.10)$ ]]; then
		sudo apt install -y zoxide exa
	fi

	sudo apt autoremove -y

	run_in_background install_rustup_ubuntu

	cd /tmp
	curl -LO https://github.com/r-darwish/topgrade/releases/latest/download/topgrade-v9.0.1-x86_64-unknown-linux-gnu.tar.gz
	tar xf topgrade-*
	sudo mv topgrade /usr/local/bin
	rm -rf topgrade-*

	sudo update-alternatives --set x-terminal-emulator /usr/bin/kitty

	if [[ "$(command -v gnome-shell)" ]]; then
		sudo -E apt install -y kitty gnome-tweaks chrome-gnome-shell gtk2-engines-murrine gnome-themes-extra sassc

		run_in_background install_gnome_extension_ubuntu
		run_in_background install_theme_ubuntu
		run_in_background install_icons_ubuntu
		run_in_background install_fonts_ubuntu
		run_in_background install_cursors_ubuntu
		run_in_background install_chrome_ubuntu

		gsettings set org.gnome.desktop.background picture-uri-dark file:///home/astadnik/Pictures/watchtower.jpg
	fi

elif [[ "$OS" = "EndeavourOS" || "$OS" = "Arch" ]]; then
	sudo pacman -Syu --noconfirm --needed git base-devel
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -sri --needed --noconfirm
	cd ..
	rm -rf .cache yay

	yay -Sy --noconfirm --answerdiff=None rustup
	rustup default stable

	yay -Sy --noconfirm --answerdiff=None git neofetch neovim python-pip tmux curl python-virtualenvwrapper fd exa telegram-desktop htop zsh zoxide bat pyright rust-analyzer openssh python-pip neovim-remote unzip npm figlet topgrade

	if [[ "$(command -v gnome-shell)" ]]; then
		run_in_background install_gnome_deps_arch

		gsettings set org.gnome.desktop.background picture-uri-dark file:///home/astadnik/Pictures/watchtower.jpg
	fi

fi

git config --global url."https://github.com/".insteadOf 'git@github.com:'
yadm submodule update --init --recursive
git config --global user.email "stadnikandriy1@gmail.com"
git config --global user.name "Stadnik Andrii"

~/.local/bin/theme_switch || true

ssh-keygen -t ed25519 -q -N "" -f ~/.ssh/id_ed25519

export TMUX_PLUGIN_MANAGER_PATH='$HOME/.tmux/plugins/'
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# ~/.tmux/plugins/tpm/bin/install_plugins

# Install Packer
topgrade -y
