#!/usr/bin/env bash

set -e

OS=$(cut -f2 <<<$(lsb_release -i))

# Confirm sudo
sudo echo

if [[ "$OS" = "Ubuntu" ]]; then
	VERSION=$(cut -f2 <<<$(lsb_release -r))

  sudo apt install -y software-properties-common
	sudo add-apt-repository ppa:neovim-ppa/unstable -y
	#sudo add-apt-repository ppa:papirus/papirus -y
	sudo apt update
	sudo apt upgrade -y

	if [[ "$VERSION" = "20.04" ]]; then
		sudo apt install -y build-essential papirus-icon-theme neofetch kitty python3-pip tmux curl python3-virtualenvwrapper fd-find telegram-desktop htop systemd-coredump gnome-tweaks zsh bat unar neovim unzip
	elif [[ "$VERSION" = "22.04" || "$VERSION" = "22.10" ]]; then
		sudo apt install -y build-essential papirus-icon-theme neofetch kitty python3-pip tmux curl python3-virtualenvwrapper fd-find telegram-desktop htop systemd-coredump gnome-tweaks zsh zoxide exa bat unar neovim unzip
	else
		echo "Unknown Ubuntu"
		exit 1
	fi

  curl -LO https://github.com/r-darwish/topgrade/releases/latest/download/topgrade-v9.0.1-x86_64-unknown-linux-gnu.tar.gz
  tar xf topgrade-*
  sudo mv topgrade /usr/local/bin

	sudo apt autoremove -y
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

	sudo update-alternatives --set x-terminal-emulator /usr/bin/kitty

	# # TODO: Check if folder exists <07-06-22, astadnik> #
	# if [[ ! -d ~/.fonts ]]; then
	# 	cd /tmp
	# 	curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
	# 	unar JetBrainsMono.zip
	# 	rm -rf ~/.fonts
	# 	mkdir ~/.fonts
	# 	mv /tmp/JetBrainsMono/*.ttf ~/.fonts/
	# 	fc-cache -fv
	# fi
	#
	# if [[ ! -d ~/.themes ]]; then
	# 	curl -LO https://github.com/EliverLara/Nordic/releases/download/v2.1.0/Nordic-v40.tar.xz
	# 	unar Nordic-v40.tar.xz
	# 	rm -rf ~/.themes
	# 	mkdir ~/.themes
	# 	mv /tmp/Nordic-v40 ~/.themes/
	# fi
	#
	# if [[ ! -d ~/.icons ]]; then
	# 	rm -rf ~/.icons
	# 	mkdir ~/.icons
	# 	wget -cO- https://github.com/phisch/phinger-cursors/releases/latest/download/phinger-cursors-variants.tar.bz2 | tar xfj - -C ~/.icons
	# fi
	#
	# git clone https://github.com/Adapta-Projects/Papirus-Nord
	# cd Papirus-Nord
	# sudo ./papirus-folders -t Papirus-Dark
	# sudo sh -c "yes | ./install"
elif [[ "$OS" = "EndeavourOS" || "$OS" = "Arch" ]]; then
	sudo pacman -Syu --noconfirm --needed git base-devel
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -sri --needed --noconfirm
	cd ..
	rm -rf .cache yay

	yay -Sy --noconfirm --answerdiff=None git neofetch kitty neovim python-pip tmux curl python-virtualenvwrapper fd exa telegram-desktop htop zsh zoxide papirus-nord nerd-fonts-jetbrains-mono phinger-cursors papirus-nord bat pyright rustup rust-analyzer openssh python-pip gtk3 gtk4 neovim-remote unzip npm figlet topgrade
else
	echo "Unknown distro"
	exit 1
fi

~/.local/bin/theme_switch || true

git config --global user.email "stadnikandriy1@gmail.com"
git config --global user.name "Stadnik Andrii"

ssh-keygen -t ed25519 -q -N "" -f ~/.ssh/id_ed25519

export TMUX_PLUGIN_MANAGER_PATH='$HOME/.tmux/plugins/'
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# ~/.tmux/plugins/tpm/bin/install_plugins

/home/astadnik/.cargo/bin/rustup default nightly

# Install Packer
topgrade -y
# nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
# nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
# nvim --headless -c 'TSUpdateSync' -c 'sleep 300' -c 'qa'
