[sys]
categories = [
    'algorithms',
    'concurrency',
    'database',
    'shell',
]
langs = [
    'python',
    'rust',
]

[sys.urls]
favorite_delete = 'https://leetcode.com/list/api/questions/$hash/$id'
favorites = 'https://leetcode.com/list/api/questions'
verify = 'https://leetcode.com/submissions/detail/$id/check/'
problem = 'https://leetcode.com/problems/$slug/description/'
test = 'https://leetcode.com/problems/$slug/interpret_solution/'
base = 'https://leetcode.com'
problems = 'https://leetcode.com/api/problems/$category/'
graphql = 'https://leetcode.com/graphql'
submission = 'https://leetcode.com/submissions/detail/$id/'
submissions = 'https://leetcode.com/api/submissions/$slug'
tag = 'https://leetcode.com/tag/$slug/'
session = 'https://leetcode.com/session/'
login = 'https://leetcode.com/accounts/login/'
submit = 'https://leetcode.com/problems/$slug/submit/'

[code]
editor = 'nvim'
edit_code_marker = false
start_marker = '@lc code=start'
end_marker = '@lc code=start'
comment_problem_desc = false
comment_leading = '///'
test = true
lang = 'rust'
pick = '${fid}.${slug}'
submission = '${fid}.${slug}.${sid}.${ac}'

[cookies]
csrf = ''
session = ''

[storage]
cache = 'cache'
code = 'code'
root = '~/.leetcode'
scripts = 'scripts'
