[code]
editor = 'nvim'
# Optional parameter
# editor-args = ['-nw']
lang = 'rust'

[cookies]
csrf = ''
session = ''

[storage]
cache = 'Problems'
code = 'code'
root = '~/.leetcode'
scripts = 'scripts'
